name: Release to Firebase on versionName change

on:
  push:
    paths:
      - '**/build.gradle'
      - '**/build.gradle.kts'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if versionName changed
        id: version_check
        run: |
          PREV_VERSION=$(git show HEAD^:app/build.gradle | grep versionName | head -1 | sed 's/.*versionName[[:space:]]*["'\'']\([^"'\'']*\)["'\''].*/\1/')
          CURR_VERSION=$(grep versionName app/build.gradle | head -1 | sed 's/.*versionName[[:space:]]*["'\'']\([^"'\'']*\)["'\''].*/\1/')
          echo "Previous version: $PREV_VERSION"
          echo "Current version: $CURR_VERSION"
          if [ "$PREV_VERSION" = "$CURR_VERSION" ]; then
            echo "versionName did not change. Skipping release."
            exit 1
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test
        run: ./gradlew test

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: app/build/outputs/apk/release/app-release-unsigned.apk