name: Run Tests

on: [push]

jobs:
  test:
    # Only run if the commit message does NOT contain "version bump"
    if: "!contains(github.event.head_commit.message, 'version bump')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build and test
        run: ./gradlew test